### ISSUE TITLE
Server is not starting

### ISSUE THREAD

**Issue by B4RD4k** [nccgroup/house#15] opened 2018-11-28 14:54 UTC
Hello, 
i installed the tool and fire it up using the command 
python app.py 1337 using PIPENV and than the server returns blank screen.

**Comment by H4oK3** [comment] 2018-12-18 00:55
Hey, I do not know what is the root cause for not working on your side. It works on my end, can you try to find more information about it?

1. Check dev tools in your browser and see if any errors being raised.
2. Check your terminal, if any errors raised there.

I am going to close this for now as it is for your individual case only but I can follow up on the thread if you need more help.

**Closed by H4oK3** 2018-12-18 00:55 UTC
